### ISSUE TITLE
数据库图片训练中的一个问题

### ISSUE THREAD

**Issue by GungnirASHTTTTT** [bubbliiiing/keras-face-recognition#5]
当我加入多张图片进入数据库时，出现了这个错误：
“
Traceback (most recent call last):
  File "G:/Python_Project/Tensorflow_FaceNet_one/face_recognize.py", line 136, in <module>
    dududu = face_rec()
  File "G:/Python_Project/Tensorflow_FaceNet_one/face_recognize.py", line 56, in __init__
    crop_img, _ = utils.Alignment_1(crop_img,landmark)
  File "G:\Python_Project\Tensorflow_FaceNet_one\utils\utils.py", line 232, in Alignment_1
    new_img = cv2.warpAffine(img, RotationMatrix, (img.shape[1], img.shape[0]))
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-i1s8y2i1\opencv\modules\imgproc\src\imgwarp.cpp:2595: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

”
该错误发生在openCV的warpAffine的翻转（仿射转换）中，我查阅了许多资料，绝大多数结论认为该错误的出现是源于序列错误或则路径错误，我找不到可以修复它的方式，我对此感到迷惑，希望能得到您的回复。

**Comment by GungnirASHTTTTT** [comment]
还有一个问题，当openCV摄像头窗口启动后，它的非常容易卡顿，并且经常处于无响应的情况。我参考了您在Bilibili中的投稿视频，显然我本地的性能并没有达到那么高，关于这一点有可以解决问题的方法吗？

上文中最后一段的表述改为：该错误发生在openCV的warpAffine的翻转（仿射转换）中，我查阅了许多资料，据认为该错误的出现是源于序列错误或则路径错误，我找不到修复它的方式（溯源不到那张加载的图片出了问题），我对此感到迷惑，希望能得到您的回复。

**Comment by bubbliiiing** [comment]
emm？你的输入图片为空？你print一下图片名字看看是哪张

**Comment by GungnirASHTTTTT** [comment]
> emm？你的输入图片为空？你print一下图片名字看看是哪张

我用排除法找到了这一张异常的照片，事实上我也没有想到单张照片有这么大的杀伤力hhh 它成功导致了内存暴涨然后断言中断

**Comment by GungnirASHTTTTT** [comment]
> emm？你的输入图片为空？你print一下图片名字看看是哪张

这有没有可能是一个个例？至少在我加载其它照片的时候没有出现类似的问题。

我在复现和使用这个项目的源码时，openCV的效率非常低，经常性卡死，无响应，这种不流畅的情况我找不到相关的理由。我在我舍友的电脑上做了尝试，他也有类似情况（按照Readme执行源码也是一样）。
我能发现的几个可能性特征之一就是cpu和显卡的利用率非常低（CPU：2600X，GPU RTX2060），我想请教在你的电脑上也会出现类似的情况吗？

期待你的回复

**Comment by bubbliiiing** [comment]
卡死是怎么呢，是检测到内容什么的吗，mtcnn代码比较久了，建议用新的retinaface来检测人脸更合理其实

**Comment by GungnirASHTTTTT** [comment]
> 卡死是怎么呢，是检测到内容什么的吗，mtcnn代码比较久了，建议用新的retinaface来检测人脸更合理其实

是opCV的窗体卡死，程序还是正常跑的。
主要表现是当桌面openCV窗体开启后就出现了无响应情况，或间断性的刷新内容。
cpugpu的占用都非常低，不知道为什么openCV的窗体会间歇性出现无响应的情况hhh
----------------------------------------------------------------------------------------------------------------------------------------------
您说的retinaface是类似于MTcnn的一中检测人脸的方案吗？
我是一名初学者，对这人脸识别和卷积，已经基本复现了MTCNN，对于retinaface还是第一次听到，您有出相关的介绍文献可供参考吗？
如有愚笨之处还请您不吝啬赐教，期待你的回复

**Comment by bubbliiiing** [comment]
我也不太清楚为什么，一般我运行都没有什么卡死的情况，是不是配置问题，retinaface我有博客，你可以直接看
